# Generated by Django 5.0 on 2023-12-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
