# Generated by Django 5.0 on 2023-12-10 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('messaging', '0002_application_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='config.application'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
