# Generated by Django 5.0 on 2023-12-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_task_application_delete_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
